<a href="https://colab.research.google.com/github/MuhammadShavaiz/pytorch-google-colab/blob/main/pytorchprac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
x = torch.tensor(([1,2,3],[2,3,5]))
print(x.shape)
print(x.ndim)

torch.Size([2, 3])
2


In [6]:
y = torch.rand(2,3)
y

tensor([[0.3085, 0.9521, 0.3777],
        [0.2675, 0.8790, 0.0396]])

In [7]:
y.dtype

torch.float32

In [8]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
zeroes = torch.zeros(2,3)
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
random_tensor = torch.rand(2, 4, dtype=torch.float32, device=torch.device('cpu'), requires_grad=False)
random_tensor

tensor([[0.8508, 0.7429, 0.8477, 0.3670],
        [0.3493, 0.9767, 0.9890, 0.0402]])

In [22]:
random_tensor2 = torch.zeros_like(random_tensor, dtype = torch.float16, device = torch.device('cpu'), requires_grad=False)
random_tensor2
random_tensor2.dtype

torch.float16

In [24]:
random_tensor2 = random_tensor2.type(torch.float32)
random_tensor2.dtype

torch.float32

addtion = just plus two tensors - or use pytorch torch.add
substraction = just subtract two tensors or use pytorch torch.subtract
scalar multiplication = multiply two tensors * or use pytorch torch.mul()
matrix multiplication = use either slow for loop or use pytoch torch.matmul()


In [26]:
tensorA = torch.tensor([[2,3,3],[3,2,2]])
tensorA
print(tensorA.T)

tensor([[2, 3],
        [3, 2],
        [3, 2]])
