<a href="https://colab.research.google.com/github/MuhammadShavaiz/pytorch-google-colab/blob/main/pytorchprac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

In [ ]:
x = torch.tensor(([1,2,3],[2,3,5]))
print(x.shape)
print(x.ndim)

torch.Size([2, 3])
2


In [ ]:
y = torch.rand(2,3)
y

tensor([[0.3085, 0.9521, 0.3777],
        [0.2675, 0.8790, 0.0396]])

In [ ]:
y.dtype

torch.float32

In [ ]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
zeroes = torch.zeros(2,3)
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
random_tensor = torch.rand(2, 4, dtype=torch.float32, device=torch.device('cpu'), requires_grad=False)
random_tensor

tensor([[0.8508, 0.7429, 0.8477, 0.3670],
        [0.3493, 0.9767, 0.9890, 0.0402]])

In [ ]:
random_tensor2 = torch.zeros_like(random_tensor, dtype = torch.float16, device = torch.device('cpu'), requires_grad=False)
random_tensor2
random_tensor2.dtype

torch.float16

In [ ]:
random_tensor2 = random_tensor2.type(torch.float32)
random_tensor2.dtype

torch.float32

addtion = just plus two tensors - or use pytorch torch.add
substraction = just subtract two tensors or use pytorch torch.subtract
scalar multiplication = multiply two tensors * or use pytorch torch.mul()
matrix multiplication = use either slow for loop or use pytoch torch.matmul()


In [ ]:
tensorA = torch.tensor([[2,3,3],[3,2,2]])
tensorA
print(tensorA.T)

tensor([[2, 3],
        [3, 2],
        [3, 2]])


finding min, max, mean, sum, argmin, argmax. mean doesnot accept long data type it accepta float or complex dtype


In [5]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [10]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [14]:
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [16]:
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

In [17]:
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

reshaping, viewing, stacking, squeezing and permuting

view and permute share the same memory of the original tensor

In [46]:
x = torch.rand(1,3,4)
x

tensor([[[0.3608, 0.9249, 0.6386, 0.6550],
         [0.1590, 0.7259, 0.9482, 0.0296],
         [0.2982, 0.2619, 0.9891, 0.9321]]])

In [50]:
x.reshape(4,3)

tensor([[0.3608, 0.9249, 0.6386],
        [0.6550, 0.1590, 0.7259],
        [0.9482, 0.0296, 0.2982],
        [0.2619, 1.0000, 0.9321]])

In [49]:
z = x.view(1,3,4)
z[0,2,2] = 1
x

tensor([[[0.3608, 0.9249, 0.6386, 0.6550],
         [0.1590, 0.7259, 0.9482, 0.0296],
         [0.2982, 0.2619, 1.0000, 0.9321]]])

In [51]:
x_stacked = torch.stack((x,x,x), dim = 1)
x_stacked

tensor([[[[0.3608, 0.9249, 0.6386, 0.6550],
          [0.1590, 0.7259, 0.9482, 0.0296],
          [0.2982, 0.2619, 1.0000, 0.9321]],

         [[0.3608, 0.9249, 0.6386, 0.6550],
          [0.1590, 0.7259, 0.9482, 0.0296],
          [0.2982, 0.2619, 1.0000, 0.9321]],

         [[0.3608, 0.9249, 0.6386, 0.6550],
          [0.1590, 0.7259, 0.9482, 0.0296],
          [0.2982, 0.2619, 1.0000, 0.9321]]]])

In [52]:
x_squeezed = x.squeeze()
x_squeezed

tensor([[0.3608, 0.9249, 0.6386, 0.6550],
        [0.1590, 0.7259, 0.9482, 0.0296],
        [0.2982, 0.2619, 1.0000, 0.9321]])

In [57]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[[0.3608, 0.9249, 0.6386, 0.6550],
         [0.1590, 0.7259, 0.9482, 0.0296],
         [0.2982, 0.2619, 1.0000, 0.9321]]])

In [64]:
print(x_unsqueezed.shape)
x_permuted = x_unsqueezed.permute(2,0,1)
x_permuted.shape

torch.Size([1, 3, 4])


torch.Size([4, 1, 3])

pytorch indexing


In [67]:
a = torch.arange(1,10,1)
a_reshape = a.reshape(1,3,3)
a_reshape

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [71]:
a_reshape[0,:,2]

tensor([3, 6, 9])

numpy and pytorch

In [72]:
import numpy as np

In [74]:
array = np.arange(1.0, 8.0)
array
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [78]:
tensor1 = torch.arange(1.0, 8.0)
tensor1
array1 = tensor1.numpy()
array1

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

#reproducibility
torch.manualseed() enables same random numbers to be generated whenever the code is run

In [79]:
random_seed = 42
torch.manual_seed(random_seed)
tensora = torch.rand(2,2)
torch.manual_seed(random_seed)
tensorb = torch.rand(2,2)
print(tensora)
print(tensorb)
print(tensora == tensorb)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[True, True],
        [True, True]])


#checking for gpu

In [80]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [92]:
tensorc = torch.rand(2,2)
tensorc.device

device(type='cpu')

In [85]:
tensor_on_gpu = tensorc.to(device) #or tensorc.cuda()
tensor_on_gpu.device

device(type='cpu')

In [90]:
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu

tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])